version: 1

builds:
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64


# Optional: Clean up test-specific directories before running GoReleaser
before:
  hooks:
    - rm -rf testdata/**/.pytest_cache
