FROM golang:1.21.5 AS builder
WORKDIR /app

# Copy go mod and sum files to cache download
COPY go.mod go.sum ./
RUN go mod download

{{ range .Dependency.Components}}
COPY {{.}} {{.}}
{{end}}

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app

FROM alpine:latest
WORKDIR /app
{{ range .Envs}}
ENV {{.Key}} {{.Value}}
{{end}}
# Set up a non-root user
RUN adduser -D appuser
USER appuser
COPY --chown=appuser --from=builder /app/app .
COPY --chown=appuser service.codefly.yaml .
EXPOSE 8080
EXPOSE 9090



CMD ["./app"]
